"""
Runs every request in data/vendor_requests.json through the agent (plus the
unreliable-conditions scenarios from tool_scenarios.json) against a fresh
database, and writes a full human-readable execution log to
logs/execution_logs.md at the project root.

Run with:  cd backend && python -m scripts.generate_execution_logs
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

from app.db import Base
from app.seed import load_vendor_risk, load_vendor_documents
from app.agent import run_agent
from app.tools import injector
from app.config import DATA_DIR

OUT_PATH = Path(__file__).resolve().parent.parent.parent / "logs" / "execution_logs.md"


def fresh_db():
    engine = create_engine("sqlite:///:memory:", connect_args={"check_same_thread": False})
    Base.metadata.create_all(bind=engine)
    Session = sessionmaker(bind=engine)
    session = Session()
    load_vendor_risk(session)
    load_vendor_documents(session)
    return session


def fmt_step(s):
    lines = [f"**Step {s['step_number']}** — action: `{s['action']}`"]
    if s.get("retry_of_step"):
        lines.append(f"  _(retry of step {s['retry_of_step']})_")
    lines.append(f"  - thought: {s['thought']}")
    lines.append(f"  - input: `{json.dumps(s['action_input'])}`")
    lines.append(f"  - observation: `{json.dumps(s['observation'])}`")
    return "\n".join(lines)


def run_and_log(out, title, req, pre_hook=None):
    injector.reset()
    db = fresh_db()
    if pre_hook:
        pre_hook(db)
    out.write(f"\n## {title}\n\n")
    out.write(f"Request: `{json.dumps(req)}`\n\n")
    result = run_agent(db, req)
    out.write(f"**Final decision: {result['decision']}**  (stop reason: `{result['stopped_reason']}`)\n\n")
    out.write(f"Explanation: {result['explanation']}\n\n")
    out.write(f"Citations: {result['citations']}\n\n")
    out.write("### Trace\n\n")
    for s in result["steps"]:
        out.write(fmt_step(s) + "\n\n")
    out.write("---\n")
    db.close()
    return result


def main():
    OUT_PATH.parent.mkdir(exist_ok=True)
    requests = json.loads((DATA_DIR / "vendor_requests.json").read_text())
    seen_ids = set()

    with open(OUT_PATH, "w") as out:
        out.write("# Vendor-Assessment Agent — Execution Logs\n\n")
        out.write("Generated by `scripts/generate_execution_logs.py`. Each section is an "
                   "independent agent run against a freshly seeded database (except the "
                   "duplicate-request and unreliable-conditions sections, which reuse state "
                   "on purpose to demonstrate those behaviours).\n")

        out.write("\n# Part 1 — Every request in vendor_requests.json\n")
        for req in requests:
            key = req["request_id"]
            title = f"{req['request_id']} — {req.get('vendor_name')} / {req.get('product')}"
            if key in seen_ids:
                title += "  (duplicate submission of an already-decided request_id)"
            run_and_log(out, title, req)
            seen_ids.add(key)

        out.write("\n# Part 2 — Unreliable-conditions scenarios (explicit fault injection)\n")

        def inject_timeoutlabs(db):
            injector.set("lookup_vendor_risk", "TimeoutLabs", "primary", ["timeout"])

        run_and_log(
            out, "Scenario: primary route timeout, recovered via backup route",
            {"request_id": "SCN-TIMEOUT-RECOVERED", "vendor_name": "TimeoutLabs",
             "product": "MetricsHub", "cost": 7500,
             "intended_use": "Monitor internal system metrics", "data_type": "internal"},
            pre_hook=inject_timeoutlabs,
        )

        def inject_failware(db):
            injector.set("lookup_vendor_risk", "FailWare", "primary", ["timeout"])
            injector.set("lookup_vendor_risk", "FailWare", "backup", ["timeout"])
            injector.set("search_vendor_documents", "FailWare", "approved_repository", ["timeout"])

        run_and_log(
            out, "Scenario: every retry route times out (retries exhausted -> escalate)",
            {"request_id": "SCN-TIMEOUT-EXHAUSTED", "vendor_name": "FailWare",
             "product": "OpsMonitor", "cost": 6000,
             "intended_use": "Monitor confidential infrastructure logs", "data_type": "confidential"},
            pre_hook=inject_failware,
        )

        def inject_conflict(db):
            from app.models import VendorDocument
            db.add(VendorDocument(
                document_id="SEC-999", vendor_name="SafeCloud", product="TeamDocs",
                source_type="approved_security_assessment", authority_tier=2,
                document_date="2026-07-30", result="fail", risk_rating="high",
                content="Conflicting later assessment found critical issues.",
            ))
            db.commit()

        run_and_log(
            out, "Scenario: two current tier-2 sources conflict on a material fact",
            {"request_id": "SCN-CONFLICT", "vendor_name": "SafeCloud", "product": "TeamDocs",
             "cost": 8000, "intended_use": "Store confidential client files",
             "data_type": "confidential"},
            pre_hook=inject_conflict,
        )

        out.write("\n## Scenario: duplicate request_id (submitted twice in one session)\n\n")
        injector.reset()
        db = fresh_db()
        dup_req = {"request_id": "SCN-DUPLICATE", "vendor_name": "DuplicateCo",
                   "product": "FlowDesk", "cost": 6500,
                   "intended_use": "Manage internal workflow tasks", "data_type": "internal"}
        r1 = run_agent(db, dup_req)
        out.write(f"First run  -> decision={r1['decision']}, steps={len(r1['steps'])}, "
                   f"stop_reason={r1['stopped_reason']}\n\n")
        r2 = run_agent(db, dup_req)
        out.write(f"Second run -> decision={r2['decision']}, steps={len(r2['steps'])}, "
                   f"stop_reason={r2['stopped_reason']} (no tools re-invoked; existing "
                   f"decision reused)\n\n")
        db.close()

    print(f"Wrote {OUT_PATH}")


if __name__ == "__main__":
    main()
